/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZapRouteImport } from './routes/zap'
import { Route as MyPhotosRouteImport } from './routes/my-photos'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNexuspagWebhookRouteImport } from './routes/api/public/nexuspag-webhook'

const ZapRoute = ZapRouteImport.update({
  id: '/zap',
  path: '/zap',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPhotosRoute = MyPhotosRouteImport.update({
  id: '/my-photos',
  path: '/my-photos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNexuspagWebhookRoute =
  ApiPublicNexuspagWebhookRouteImport.update({
    id: '/api/public/nexuspag-webhook',
    path: '/api/public/nexuspag-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-photos': typeof MyPhotosRoute
  '/zap': typeof ZapRoute
  '/api/public/nexuspag-webhook': typeof ApiPublicNexuspagWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-photos': typeof MyPhotosRoute
  '/zap': typeof ZapRoute
  '/api/public/nexuspag-webhook': typeof ApiPublicNexuspagWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/my-photos': typeof MyPhotosRoute
  '/zap': typeof ZapRoute
  '/api/public/nexuspag-webhook': typeof ApiPublicNexuspagWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/my-photos'
    | '/zap'
    | '/api/public/nexuspag-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/my-photos' | '/zap' | '/api/public/nexuspag-webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/my-photos'
    | '/zap'
    | '/api/public/nexuspag-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  MyPhotosRoute: typeof MyPhotosRoute
  ZapRoute: typeof ZapRoute
  ApiPublicNexuspagWebhookRoute: typeof ApiPublicNexuspagWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zap': {
      id: '/zap'
      path: '/zap'
      fullPath: '/zap'
      preLoaderRoute: typeof ZapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-photos': {
      id: '/my-photos'
      path: '/my-photos'
      fullPath: '/my-photos'
      preLoaderRoute: typeof MyPhotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/nexuspag-webhook': {
      id: '/api/public/nexuspag-webhook'
      path: '/api/public/nexuspag-webhook'
      fullPath: '/api/public/nexuspag-webhook'
      preLoaderRoute: typeof ApiPublicNexuspagWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  MyPhotosRoute: MyPhotosRoute,
  ZapRoute: ZapRoute,
  ApiPublicNexuspagWebhookRoute: ApiPublicNexuspagWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
